--This file makes all the clients download all the files.
--You don't want clients to download?
--Then just delete this file!



--------------------------SCARS
--Airboata Seat
resource.AddFile( "models/nova/airboat_seat.mdl" )

//Materials
--Bobcat
resource.AddFile( "materials/models/bobcat/1.vmt" )
resource.AddFile( "materials/models/bobcat/1_normal.vtf" )
resource.AddFile( "materials/models/bobcat/78.vmt" )
resource.AddFile( "materials/models/bobcat/78.vmt" )
resource.AddFile( "materials/models/bobcat/78_normal.vtf" )
resource.AddFile( "materials/models/bobcat/bobcat_badges.vmt" )
resource.AddFile( "materials/models/bobcat/bobcat_interior.vmt" )
resource.AddFile( "materials/models/bobcat/bobcat_lights_glass.vmt" )
resource.AddFile( "materials/models/bobcat/bobcat_lights_glass_normal.vtf" )
resource.AddFile( "materials/models/bobcat/vehicle_generic_detail2.vmt" )
resource.AddFile( "materials/models/bobcat/vehicle_generic_detail2_normal.vtf" )
resource.AddFile( "materials/models/bobcat/vehicle_generic_glasswindows2.vmt" )
resource.AddFile( "materials/models/bobcat/vehicle_generic_glasswindows2_normal.vtf" )
resource.AddFile( "materials/models/bobcat/vehicle_generic_tyrewallblack.vmt" )
resource.AddFile( "materials/models/bobcat/vehicle_generic_tyrewallblack_normal.vtf" )

--Borderlands
resource.AddFile( "materials/models/Borderlands/Bus/BusExterior1.vmt" )
resource.AddFile( "materials/models/Borderlands/Bus/BusExterior2.vmt" )
resource.AddFile( "materials/models/Borderlands/Bus/BusSkin1.vmt" )
resource.AddFile( "materials/models/Borderlands/Bus/BusSkin2.vmt" )
resource.AddFile( "materials/models/Borderlands/Bus/Special/BusSkin1-BumpMap.vmt" )
resource.AddFile( "materials/models/Borderlands/Bus/Special/BusSkin2-BumpMap.vmt" )

--Chaos
resource.AddFile( "materials/models/Chaos126p/Chaos126p.vmt" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_blue.vmt" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_red.vmt" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_blue_ilumination.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_blue_lightwarp.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_red_ilumination.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_red_lightwarp.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_ilumination.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_lightwarp.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_normal01.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_red_skin_normal.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_blue_ilumination.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_blue_lightwarp.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_ilumination.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_lightwarp.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_normal01.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_red_ilumination.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_red_lightwarp.vtf" )
resource.AddFile( "materials/models/Chaos126p/Chaos126p_red_skin_normal.vtf" )

--Hedgehog
resource.AddFile( "materials/models/Hedgehog/Hedgehog.vmt" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_blue.vmt" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_destroyed.vmt" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_red.vmt" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_blue_ilumination.vtf" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_blue_lightwarp.vtf" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_lightwarp.vtf" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_normal.vtf" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_red_ilumination.vtf" )
resource.AddFile( "materials/models/Hedgehog/Hedgehog_red_lightwarp.vtf" )

--Huntley
resource.AddFile( "materials/models/huntley/huntley_badges.vmt" )
resource.AddFile( "materials/models/huntley/78.vmt" )
resource.AddFile( "materials/models/huntley/cavalvade_interior.vmt" )
resource.AddFile( "materials/models/huntley/huntley_lights.vmt" )
resource.AddFile( "materials/models/huntley/78_normal.vmt" )
resource.AddFile( "materials/models/huntley/vehicle_generic_detail2.vmt" )
resource.AddFile( "materials/models/huntley/vehicle_generic_glasswindows2.vmt" )
resource.AddFile( "materials/models/huntley/vehicle_generic_tyrewallblack.vmt" )
resource.AddFile( "materials/models/huntley/vehicle_generic_detail2_normal.vtf" )
resource.AddFile( "materials/models/huntley/vehicle_generic_glasswindows2_normal.vtf" )
resource.AddFile( "materials/models/huntley/vehicle_generic_tyrewallblack_normal.vtf" )


--Ratmobile
resource.AddFile( "materials/models/Ratmobile/Ratmobile.vmt" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_blue.vmt" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_destroyed.vmt" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_red.vmt" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_blue_ilumination.vtf" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_ilumination.vtf" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_lightwarp.vtf" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_normal.vtf" )
resource.AddFile( "materials/models/Ratmobile/Ratmobile_red_ilumination.vtf" )


--sabregt
resource.AddFile( "materials/models/sabregt/sabregt_badges.vmt" )
resource.AddFile( "materials/models/sabregt/sabregt_interior.vmt" )
resource.AddFile( "materials/models/sabregt/sabreturbo_lights_glass.vmt" )
resource.AddFile( "materials/models/sabregt/skin2.vmt" )
resource.AddFile( "materials/models/sabregt/skin3.vmt" )
resource.AddFile( "materials/models/sabregt/skin4.vmt" )
resource.AddFile( "materials/models/sabregt/skin5.vmt" )
resource.AddFile( "materials/models/sabregt/skin6.vmt" )
resource.AddFile( "materials/models/sabregt/steed_black.vmt" )
resource.AddFile( "materials/models/sabregt/vehicle_generic_detail2.vmt" )
resource.AddFile( "materials/models/sabregt/vehicle_generic_glasswindows2.vmt" )
resource.AddFile( "materials/models/sabregt/vehicle_generic_tyrewallblack.vmt" )
resource.AddFile( "materials/models/sabregt/steed_black_normal.vtf" )
resource.AddFile( "materials/models/sabregt/vehicle_generic_detail2_normal.vtf" )
resource.AddFile( "materials/models/sabregt/vehicle_generic_glasswindows2_normal.vtf" )

--seat_m
resource.AddFile( "materials/models/seat_m/seat_D_B.vmt" )
resource.AddFile( "materials/models/seat_m/seat_D_G.vmt" )
resource.AddFile( "materials/models/seat_m/seat_D_R.vmt" )
resource.AddFile( "materials/models/seat_m/seat_NS.vtf" )

--taxi
resource.AddFile( "materials/models/taxi/noose_lights.vmt" )
resource.AddFile( "materials/models/taxi/rom_stickers.vmt" )
resource.AddFile( "materials/models/taxi/taxi_badges.vmt" )
resource.AddFile( "materials/models/taxi/taxi_detail.vmt" )
resource.AddFile( "materials/models/taxi/taxi_signs_1.vmt" )
resource.AddFile( "materials/models/taxi/taxi_signs_1_normal.vmt" )
resource.AddFile( "materials/models/taxi/taxicolor.vmt" )
resource.AddFile( "materials/models/taxi/taxicolor_normal.vmt" )
resource.AddFile( "materials/models/taxi/vehicle_generic_detail2.vmt" )
resource.AddFile( "materials/models/taxi/vehicle_generic_glasswindows2.vmt" )
resource.AddFile( "materials/models/taxi/vehicle_generic_interior.vmt" )
resource.AddFile( "materials/models/taxi/vehicle_generic_tyrewallblack.vmt" )
resource.AddFile( "materials/models/taxi/vehicle_generic_detail2_normal.vtf" )
resource.AddFile( "materials/models/taxi/vehicle_generic_glasswindows2_normal.vtf" )
resource.AddFile( "materials/models/taxi/vehicle_generic_tyrewallblack_normal.vtf" )

-----------vigilante8

--Clydesdale
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks.vmt" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks_3.vmt" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks_6.vmt" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks_glass.vmt" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks6.vmt" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/flat_normal.vtf" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks.vmt" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks_6.vmt" )
resource.AddFile( "materials/models/vigilante8/Clydesdale/pickup_trucks_3_normal.vtf" )

--MothTruck
resource.AddFile( "materials/models/vigilante8/MothTruck/flatnose_truck.vmt" )
resource.AddFile( "materials/models/vigilante8/MothTruck/flatnose_truck_glass.vmt" )
resource.AddFile( "materials/models/vigilante8/MothTruck/flatnose_truck_normal.vtf" )
resource.AddFile( "materials/models/vigilante8/MothTruck/flat_normal.vtf" )

--StagPickup
resource.AddFile( "materials/models/vigilante8/StagPickup/beeplate.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/bf.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/black_396.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Body1.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Body2.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Body3.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Chrome.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/extras.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/gm_engine.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/metal_door_02.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/tekstura.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Trailerside.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Trailersidestripe.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/vehicle_generic_chrome_colour.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/vehicle_generic_detail2.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/vehicle_generic_glasswindows2.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/vehiclelights128.vmt" )
resource.AddFile( "materials/models/vigilante8/StagPickup/beeplate_normal.vtf" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Body_normal.vtf" )
resource.AddFile( "materials/models/vigilante8/StagPickup/body3.vtf" )
resource.AddFile( "materials/models/vigilante8/StagPickup/chrome_norm.vtf" )
resource.AddFile( "materials/models/vigilante8/StagPickup/flat_normal.vtf" )
resource.AddFile( "materials/models/vigilante8/StagPickup/Trailerside_normal.vtf" )
resource.AddFile( "materials/models/vigilante8/StagPickup/vehicle_generic_glasswindows.vtf" )
resource.AddFile( "materials/models/vigilante8/StagPickup/vehicle_generic_glasswindows2_normal.vtf" )

--gtaiv
resource.AddFile( "materials/models/gtaiv/vehicles/black.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/blue.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/green.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/red.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_carbon.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_detail2.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_doorshut.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_glasswindows2.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_tyrewallblack.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/white.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/yellow.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/color_normal.vtf" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_carbon_normal.vtf" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_detail2_normal.vtf" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_doorshut_normal.vtf" )
resource.AddFile( "materials/models/gtaiv/vehicles/vehicle_generic_tyrewall_normal.vtf" )

--banshee
resource.AddFile( "materials/models/gtaiv/vehicles/banshee/banshee_badges.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/banshee/banshee_interior.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/banshee/banshee_lights_glass.vmt" )

--comet
resource.AddFile( "materials/models/gtaiv/vehicles/comet/black.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/blue.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/comet_badges.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/comet_interior.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/comet_lights.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/gaybow.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/green.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/red.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/white.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/yellow.vmt" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/gaybow_n.vtf" )
resource.AddFile( "materials/models/gtaiv/vehicles/comet/comet_badges_n.vtf" )

--Misc materials
resource.AddFile( "materials/SCarHUD/fuelPointer.vmt" )
resource.AddFile( "materials/SCarHUD/gear.vmt" )
resource.AddFile( "materials/SCarHUD/rev.vmt" )
resource.AddFile( "materials/SCarHUD/speed.vmt" )
resource.AddFile( "materials/SCarHUD/speedPointer.vmt" )
resource.AddFile( "materials/SCarHUD/weaponHud.vmt" )

--Splayn
resource.AddFile( "materials/Splayn/chrome.vmt" )
resource.AddFile( "materials/Splayn/imp_s2.vmt" )
resource.AddFile( "materials/Splayn/imp_s3.vmt" )
resource.AddFile( "materials/Splayn/imp_s4.vmt" )
resource.AddFile( "materials/Splayn/imp_s5.vmt" )
resource.AddFile( "materials/Splayn/imp_s6.vmt" )
resource.AddFile( "materials/Splayn/imp01.vmt" )
resource.AddFile( "materials/Splayn/imp02.vmt" )
resource.AddFile( "materials/Splayn/imp03.vmt" )
resource.AddFile( "materials/Splayn/liner222.vmt" )
resource.AddFile( "materials/Splayn/tireimp.vmt" )
resource.AddFile( "materials/Splayn/window.vmt" )
resource.AddFile( "materials/Splayn/imp_env.vtf" )
resource.AddFile( "materials/Splayn/liner_env.vtf" )

--Belair
resource.AddFile( "materials/Splayn/belair/black64.vmt" )
resource.AddFile( "materials/Splayn/belair/body2.vmt" )
resource.AddFile( "materials/Splayn/belair/Body3.vmt" )
resource.AddFile( "materials/Splayn/belair/Body4.vmt" )
resource.AddFile( "materials/Splayn/belair/body5.vmt" )
resource.AddFile( "materials/Splayn/belair/FF0000FF.vmt" )
resource.AddFile( "materials/Splayn/belair/FF6B6B6E.vmt" )
resource.AddFile( "materials/Splayn/belair/FF00628E.vmt" )
resource.AddFile( "materials/Splayn/belair/FFFF0000.vmt" )
resource.AddFile( "materials/Splayn/belair/FFFFFFFF.vmt" )
resource.AddFile( "materials/Splayn/belair/Glass.vmt" )
resource.AddFile( "materials/Splayn/belair/grey64.vmt" )
resource.AddFile( "materials/Splayn/belair/lm01.vmt" )
resource.AddFile( "materials/Splayn/belair/main.vmt" )
resource.AddFile( "materials/Splayn/belair/mychref.vmt" )
resource.AddFile( "materials/Splayn/belair/Numberplate.vmt" )
resource.AddFile( "materials/Splayn/belair/red64.vmt" )
resource.AddFile( "materials/Splayn/belair/tirelm.vmt" )
resource.AddFile( "materials/Splayn/belair/vehiclelights128.vmt" )
resource.AddFile( "materials/Splayn/belair/lack.vtf" )
resource.AddFile( "materials/Splayn/belair/liner_env.vtf" )

--Caddilac
resource.AddFile( "materials/Splayn/Caddilac/59caddy.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/black.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/body2.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/Body3.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/Body4.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/body5.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/Crome.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/FFFFFFFF.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/Glass.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/vehiclelights128.vmt" )
resource.AddFile( "materials/Splayn/Caddilac/liner_env.vtf" )
resource.AddFile( "materials/Splayn/Caddilac/lack.vtf" )
resource.AddFile( "materials/Splayn/Caddilac/cad_env.vtf" )

--camaro
resource.AddFile( "materials/Splayn/camaro/3C666666.vmt" )
resource.AddFile( "materials/Splayn/camaro/body2.vmt" )
resource.AddFile( "materials/Splayn/camaro/BODY3.vmt" )
resource.AddFile( "materials/Splayn/camaro/BODY4.vmt" )
resource.AddFile( "materials/Splayn/camaro/BODY5.vmt" )
resource.AddFile( "materials/Splayn/camaro/camabody.vmt" )
resource.AddFile( "materials/Splayn/camaro/camaro1.vmt" )
resource.AddFile( "materials/Splayn/camaro/camaro2.vmt" )
resource.AddFile( "materials/Splayn/camaro/camaro3.vmt" )
resource.AddFile( "materials/Splayn/camaro/camaro4.vmt" )
resource.AddFile( "materials/Splayn/camaro/FF060606.vmt" )
resource.AddFile( "materials/Splayn/camaro/FF999999.vmt" )
resource.AddFile( "materials/Splayn/camaro/FFB4B4B4.vmt" )
resource.AddFile( "materials/Splayn/camaro/Glass.vmt" )
resource.AddFile( "materials/Splayn/camaro/numberplate.vmt" )
resource.AddFile( "materials/Splayn/camaro/remap_body.vmt" )
resource.AddFile( "materials/Splayn/camaro/tyre.vmt" )
resource.AddFile( "materials/Splayn/camaro/vehiclegeneric256.vmt" )
resource.AddFile( "materials/Splayn/camaro/vehiclelightsspl.vmt" )
resource.AddFile( "materials/Splayn/camaro/body_env.vtf" )
resource.AddFile( "materials/Splayn/camaro/liner_env.vtf" )

--Police impala
resource.AddFile( "materials/Splayn/cars/police_impala/badge.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/chrome.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/glass.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/imp01.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/imp02.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/imp03.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/liner_2.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/liner222.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/off.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/on.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/plastik_grau.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/plexi_blau.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/plexi_rot.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/plexi_weiss.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/sign.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/silber.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/tireimp.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/window.vmt" )
resource.AddFile( "materials/Splayn/cars/police_impala/imp_env.vtf" )
resource.AddFile( "materials/Splayn/cars/police_impala/liner_env.vtf" )

--chevy66
resource.AddFile( "materials/Splayn/chevy66/black.vmt" )
resource.AddFile( "materials/Splayn/chevy66/boden.vmt" )
resource.AddFile( "materials/Splayn/chevy66/darkgrey.vmt" )
resource.AddFile( "materials/Splayn/chevy66/engine.vmt" )
resource.AddFile( "materials/Splayn/chevy66/Innerself.vmt" )
resource.AddFile( "materials/Splayn/chevy66/leather.vmt" )
resource.AddFile( "materials/Splayn/chevy66/ledera.vmt" )
resource.AddFile( "materials/Splayn/chevy66/lederb.vmt" )
resource.AddFile( "materials/Splayn/chevy66/orange.vmt" )
resource.AddFile( "materials/Splayn/chevy66/plateback1.vmt" )
resource.AddFile( "materials/Splayn/chevy66/profil.vmt" )
resource.AddFile( "materials/Splayn/chevy66/red.vmt" )
resource.AddFile( "materials/Splayn/chevy66/remappremier92body128.vmt" )
resource.AddFile( "materials/Splayn/chevy66/shegrey.vmt" )
resource.AddFile( "materials/Splayn/chevy66/tex1.vmt" )
resource.AddFile( "materials/Splayn/chevy66/tex2.vmt" )
resource.AddFile( "materials/Splayn/chevy66/white.vmt" )
resource.AddFile( "materials/Splayn/chevy66/white_s.vmt" )
resource.AddFile( "materials/Splayn/chevy66/white64.vmt" )
resource.AddFile( "materials/Splayn/chevy66/whitea128.vmt" )
resource.AddFile( "materials/Splayn/chevy66/windscreen.vmt" )
resource.AddFile( "materials/Splayn/chevy66/wood50.vmt" )
resource.AddFile( "materials/Splayn/chevy66/body_env.vtf" )
resource.AddFile( "materials/Splayn/chevy66/chrome.vtf" )
resource.AddFile( "materials/Splayn/chevy66/tex2_env.vtf" )
resource.AddFile( "materials/Splayn/chevy66/Wood_env.vtf" )

--FMFGT
resource.AddFile( "materials/Splayn/FMFGT/661C1C1C.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/bfgood.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bodytex.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bodytex_2.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bodytex_3.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bodytex_4.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bodytex_5.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bullitt1.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bullitt2.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Bullitt3.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Carpet.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Carpet2.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/chrome.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Discbrake.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/FF000000.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/FF00006E.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/FF696969.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/FFFFFFFF.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/Glass.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/tyre64a.vmt" )
resource.AddFile( "materials/Splayn/FMFGT/liner_env.vtf" )

--fordgt
resource.AddFile( "materials/Splayn/fordgt/black.vmt" )
resource.AddFile( "materials/Splayn/fordgt/body2.vmt" )
resource.AddFile( "materials/Splayn/fordgt/Body3.vmt" )
resource.AddFile( "materials/Splayn/fordgt/Body4.vmt" )
resource.AddFile( "materials/Splayn/fordgt/body5.vmt" )
resource.AddFile( "materials/Splayn/fordgt/brake.vmt" )
resource.AddFile( "materials/Splayn/fordgt/conti.vmt" )
resource.AddFile( "materials/Splayn/fordgt/conti-sc2.vmt" )
resource.AddFile( "materials/Splayn/fordgt/FORDGT_BADGING.vmt" )
resource.AddFile( "materials/Splayn/fordgt/FORDGT_ENGINE.vmt" )
resource.AddFile( "materials/Splayn/fordgt/FORDGT_INTERIOR.vmt" )
resource.AddFile( "materials/Splayn/fordgt/FORDGT_KIT00_BRAKELIGHT_OFF.vmt" )
resource.AddFile( "materials/Splayn/fordgt/FORDGT_KIT00_HEADLIGHT_ON.vmt" )
resource.AddFile( "materials/Splayn/fordgt/FORDGT_MISC.vmt" )
resource.AddFile( "materials/Splayn/fordgt/lex10.vmt" )
resource.AddFile( "materials/Splayn/fordgt/metal1.vmt" )
resource.AddFile( "materials/Splayn/fordgt/mirror_tex.vmt" )
resource.AddFile( "materials/Splayn/fordgt/remap_ford.vmt" )
resource.AddFile( "materials/Splayn/fordgt/underbody.vmt" )
resource.AddFile( "materials/Splayn/fordgt/vehiclelights128.vmt" )
resource.AddFile( "materials/Splayn/fordgt/window.vmt" )
resource.AddFile( "materials/Splayn/fordgt/lack.vtf" )
resource.AddFile( "materials/Splayn/fordgt/liner_env.vtf" )

--h2
resource.AddFile( "materials/Splayn/h2/FF262601.vmt" )
resource.AddFile( "materials/Splayn/h2/FF595959.vmt" )
resource.AddFile( "materials/Splayn/h2/FFBABA01.vmt" )
resource.AddFile( "materials/Splayn/h2/Glass.vmt" )
resource.AddFile( "materials/Splayn/h2/h2body_S1.vmt" )
resource.AddFile( "materials/Splayn/h2/h2body_S2.vmt" )
resource.AddFile( "materials/Splayn/h2/h2body_S3.vmt" )
resource.AddFile( "materials/Splayn/h2/h2body_S4.vmt" )
resource.AddFile( "materials/Splayn/h2/h2body_S5.vmt" )
resource.AddFile( "materials/Splayn/h2/h2details.vmt" )
resource.AddFile( "materials/Splayn/h2/h2inside.vmt" )
resource.AddFile( "materials/Splayn/h2/h2inside2.vmt" )
resource.AddFile( "materials/Splayn/h2/h2parts.vmt" )
resource.AddFile( "materials/Splayn/h2/wheel.vmt" )
resource.AddFile( "materials/Splayn/h2/liner_env.vtf" )

--Studebaker
resource.AddFile( "materials/Splayn/Studebaker/2obivka.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/body.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/body_chrom.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/Body2.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/Body3.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/Body4.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/Body5.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/dvigatel.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/Glass.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/IMG_1176.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/obivka.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/plate.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/pokruska.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/underbody.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/vehiclegeneric256.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/vehiclelights128.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/vette_dam.vmt" )
resource.AddFile( "materials/Splayn/Studebaker/liner_env.vtf" )

--VGUI
resource.AddFile( "materials/VGUI/wheel_Banshee.vmt" )
resource.AddFile( "materials/VGUI/wheel_belair.vmt" )
resource.AddFile( "materials/VGUI/wheel_bobcat.vmt" )
resource.AddFile( "materials/VGUI/wheel_cadillac.vmt" )
resource.AddFile( "materials/VGUI/wheel_camaro.vmt" )
resource.AddFile( "materials/VGUI/wheel_Chaos126p.vmt" )
resource.AddFile( "materials/VGUI/wheel_chevy66.vmt" )
resource.AddFile( "materials/VGUI/wheel_fordGT.vmt" )
resource.AddFile( "materials/VGUI/wheel_Hedgehog.vmt" )
resource.AddFile( "materials/VGUI/wheel_hummer.vmt" )
resource.AddFile( "materials/VGUI/wheel_huntley.vmt" )
resource.AddFile( "materials/VGUI/wheel_impala.vmt" )
resource.AddFile( "materials/VGUI/wheel_impala88.vmt" )
resource.AddFile( "materials/VGUI/wheel_junker.vmt" )
resource.AddFile( "materials/VGUI/wheel_mustang.vmt" )
resource.AddFile( "materials/VGUI/wheel_Ratmobile.vmt" )
resource.AddFile( "materials/VGUI/wheel_studebaker.vmt" )
resource.AddFile( "materials/VGUI/wheel_template.vmt" )


resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_Banshee.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_belair.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_bobcat.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_bus.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_cadillac.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_camaro.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_Chaos126p.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_chevy66.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_clydesdale.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_Comet.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_fordGT.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_Hedgehog.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_hummer.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_huntley.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_impala.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_impala88.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_junker1.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_junker2.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_junker3.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_junker4.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_mothtruck.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_mustang.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_Police.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_Ratmobile.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_Sabre.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_stagPickup.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_studebaker.vmt" )
resource.AddFile( "materials/VGUI/entities/sent_Sakarias_Car_taxi.vmt" )

//Models
resource.AddFile( "models/bobcat.mdl" )
resource.AddFile( "models/bobcatw.mdl" )
resource.AddFile( "models/huntley1.mdl" )
resource.AddFile( "models/huntleyw.mdl" )
resource.AddFile( "models/sabregt_sep.mdl" )
resource.AddFile( "models/sabregt_wheel.mdl" )
resource.AddFile( "models/taxi1.mdl" )


--Borderlands
resource.AddFile( "models/Borderlands/Bus/bus.mdl" )
resource.AddFile( "models/Borderlands/Bus/steeringframe.mdl" )

--GTA
resource.AddFile( "models/dean/gtaiv/vehicles/banshee.mdl" )
resource.AddFile( "models/dean/gtaiv/vehicles/banshee_sep.mdl" )
resource.AddFile( "models/dean/gtaiv/vehicles/bansheewheel.mdl" )
resource.AddFile( "models/dean/gtaiv/vehicles/comet.mdl" )
resource.AddFile( "models/dean/gtaiv/vehicles/comet_sep.mdl" )
resource.AddFile( "models/dean/gtaiv/vehicles/cometwheel.mdl" )


---------DIPRIP

--Chaos126p
resource.AddFile( "models/DIPRIP/Chaos126p/chaos126p.mdl" )
resource.AddFile( "models/DIPRIP/Chaos126p/chaos126p_wheel.mdl" )

--Hedgehog
resource.AddFile( "models/DIPRIP/Hedgehog/hedgehog.mdl" )
resource.AddFile( "models/DIPRIP/Hedgehog/hedgehog_wheel.mdl" )

--Ratmobile
resource.AddFile( "models/DIPRIP/Ratmobile/ratmobile.mdl" )
resource.AddFile( "models/DIPRIP/Ratmobile/ratmobile_wheel.mdl" )



--seat_m
resource.AddFile( "models/seat_m/seat_01.mdl" )
resource.AddFile( "models/seat_m/seat_01_phy.mdl" )
resource.AddFile( "models/seat_m/seat_02.mdl" )
resource.AddFile( "models/seat_m/seat_02_phy.mdl" )
resource.AddFile( "models/seat_m/seat_chairl.mdl" )
resource.AddFile( "models/seat_m/seat_chairr.mdl" )
resource.AddFile( "models/seat_m/seat_doorb.mdl" )
resource.AddFile( "models/seat_m/seat_doorl.mdl" )
resource.AddFile( "models/seat_m/seat_doorr.mdl" )
resource.AddFile( "models/seat_m/seat_glass.mdl" )
resource.AddFile( "models/seat_m/seat_glass_phy.mdl" )
resource.AddFile( "models/seat_m/seat_hood.mdl" )
resource.AddFile( "models/seat_m/seat_weel.mdl" )
resource.AddFile( "models/seat_m/seat_weel_phy.mdl" )
resource.AddFile( "models/seat_m/seat_weels.mdl" )
resource.AddFile( "models/seat_m/seat_weels_bend.mdl" )
resource.AddFile( "models/seat_m/seat_wreck.mdl" )
resource.AddFile( "models/seat_m/seat_wreck_phy.mdl" )

--Splayn
resource.AddFile( "models/Splayn/belair.mdl" )
resource.AddFile( "models/Splayn/belair_w_wh.mdl" )
resource.AddFile( "models/Splayn/belair_wheel.mdl" )
resource.AddFile( "models/Splayn/cadillac.mdl" )
resource.AddFile( "models/Splayn/cadillac_w_wh.mdl" )
resource.AddFile( "models/Splayn/cadillac_wh.mdl" )
resource.AddFile( "models/Splayn/camaro_wheel.mdl" )
resource.AddFile( "models/Splayn/camaro_wow.mdl" )
resource.AddFile( "models/Splayn/camaro_ww.mdl" )
resource.AddFile( "models/Splayn/chevy66.mdl" )
resource.AddFile( "models/Splayn/chevy66_wheel.mdl" )
resource.AddFile( "models/Splayn/ford_mustang_fastback_gt.mdl" )
resource.AddFile( "models/Splayn/fordgt.mdl" )
resource.AddFile( "models/Splayn/fordgt_w_wh.mdl" )
resource.AddFile( "models/Splayn/fordgt_wh.mdl" )
resource.AddFile( "models/Splayn/hummer_h2.mdl" )
resource.AddFile( "models/Splayn/hummerwh_h2.mdl" )
resource.AddFile( "models/Splayn/impala88.mdl" )
resource.AddFile( "models/Splayn/impala88_sep.mdl" )
resource.AddFile( "models/Splayn/impala88_wheel.mdl" )
resource.AddFile( "models/Splayn/mustang_wheel.mdl" )
resource.AddFile( "models/Splayn/studebaker_lark.mdl" )
resource.AddFile( "models/Splayn/studebaker_w_wh.mdl" )
resource.AddFile( "models/Splayn/studebaker_wh.mdl" )
resource.AddFile( "models/Splayn/cars/police_imp1.mdl" )

------Vigilante8
resource.AddFile( "models/Vigilante8/clydesdale1.mdl" )
resource.AddFile( "models/Vigilante8/mothtruck.mdl" )
resource.AddFile( "models/Vigilante8/stagpickup1.mdl" )

//Sounds
resource.AddFile( "sound/car/burnout.wav" )
resource.AddFile( "sound/car/changeGear.wav" )
resource.AddFile( "sound/car/engineStart.wav" )
resource.AddFile( "sound/car/hydraulics.wav" )
resource.AddFile( "sound/car/nosstart.wav" )
resource.AddFile( "sound/car/nosstop.wav" )
resource.AddFile( "sound/car/skid.wav" )

resource.AddFile( "sound/carStools/hydraulic.wav" )
resource.AddFile( "sound/carStools/spray.wav" )
resource.AddFile( "sound/carStools/tune.wav" )
resource.AddFile( "sound/carStools/wheel.wav" )

resource.AddFile( "sound/carStools/tire/flatTire.wav" )


