list.Set( "scar_wheels", "#Belair", { Material = "vgui/wheel_belair", wheelchanger_model = "models/Splayn/belair_wheel.mdl" , Value = "Belair" } )
list.Set( "scar_wheels", "#Cadillac", { Material = "vgui/wheel_cadillac", wheelchanger_model = "models/Splayn/cadillac_wh.mdl" , Value = "Cadillac" } )
list.Set( "scar_wheels", "#Camaro", { Material = "vgui/wheel_camaro", wheelchanger_model = "models/Splayn/camaro_wheel.mdl" , Value = "Camaro" } )
list.Set( "scar_wheels", "#Chevy 66", { Material = "vgui/wheel_chevy66", wheelchanger_model = "models/Splayn/chevy66_wheel.mdl" , Value = "Chevy 66" } )
list.Set( "scar_wheels", "#Ford GT", { Material = "vgui/wheel_fordGT", wheelchanger_model = "models/Splayn/fordgt_wh.mdl" , Value = "Ford GT" } )
list.Set( "scar_wheels", "#Hummer", { Material = "vgui/wheel_hummer", wheelchanger_model = "models/Splayn/hummerwh_h2.mdl" , Value = "Hummer" } )
list.Set( "scar_wheels", "#Mustang Fastback", { Material = "vgui/wheel_mustang", wheelchanger_model = "models/Splayn/mustang_wheel.mdl" , Value = "Mustang Fastback" } )
list.Set( "scar_wheels", "#Studebaker", { Material = "vgui/wheel_studebaker", wheelchanger_model = "models/Splayn/studebaker_wh.mdl" , Value = "Studebaker" } )
list.Set( "scar_wheels", "#Junker", { Material = "vgui/wheel_junker", wheelchanger_model = "models/props_vehicles/carparts_wheel01a.mdl" , Value = "Junker" } )
list.Set( "scar_wheels", "#Impala88", { Material = "vgui/wheel_impala88", wheelchanger_model = "models/Splayn/impala88_wheel.mdl" , Value = "Impala88" } )
list.Set( "scar_wheels", "#Banshee", { Material = "vgui/wheel_Banshee", wheelchanger_model = "models/dean/gtaiv/vehicles/bansheewheel.mdl" , Value = "Banshee" } )
list.Set( "scar_wheels", "#Huntley", { Material = "vgui/wheel_huntley", wheelchanger_model = "models/huntleyw.mdl" , Value = "Huntley" } )
list.Set( "scar_wheels", "#Bobcat", { Material = "vgui/wheel_bobcat", wheelchanger_model =  "models/bobcatw.mdl" , Value = "Bobcat" } )
list.Set( "scar_wheels", "#Ratmobile", { Material = "vgui/wheel_Ratmobile", wheelchanger_model = "models/DIPRIP/Ratmobile/Ratmobile_wheel.mdl" , Value = "Ratmobile" } )
list.Set( "scar_wheels", "#Chaos126p", { Material = "vgui/wheel_Chaos126p", wheelchanger_model = "models/DIPRIP/Chaos126p/Chaos126p_wheel.mdl" , Value = "Chaos126p" } )
list.Set( "scar_wheels", "#Hedgehog", { Material = "vgui/wheel_Hedgehog", wheelchanger_model = "models/DIPRIP/Hedgehog/Hedgehog_wheel.mdl" , Value = "Hedgehog" } )
