AddCSLuaFile( "autorun/SCarConsoleCommands.lua" ) 

CreateConVar("scar_acceleration", 10000, true, false)
CreateConVar("scar_maxspeed", 5000, true, false)
CreateConVar("scar_turborffect", 5, true, false)
CreateConVar("scar_turboduration", 10, true, false)
CreateConVar("scar_turbodelay", 1, true, false)
CreateConVar("scar_reverseforce", 5000, true, false)
CreateConVar("scar_reversemaxspeed", 1000, true, false)
CreateConVar("scar_breakefficiency", 4, true, false)
CreateConVar("scar_steerforce", 20, true, false)
CreateConVar("scar_steerresponse", 2, true, false)
CreateConVar("scar_stabilisation", 2000, true, false)
CreateConVar("scar_nrofgears", 1, true, false)
CreateConVar("scar_usert", 1, true, false)
CreateConVar("scar_usehud", 1, true, false)
CreateConVar("scar_thirdpersonview", 1, true, false)
CreateConVar("scar_fuelconsumptionuse", 1, true, false)
CreateConVar("scar_allowHydraulics", 1, true, false)
CreateConVar("scar_fuelconsumption", 1, true, false)
CreateConVar("scar_maxhealth", 1000, true, false)	
CreateConVar("scar_tiredamage", 1, true, false)
CreateConVar("scar_cardamage", 1, true, false)
CreateConVar("scar_maxscars", 10, true, false)
CreateConVar("scar_maxantislide", 200, true, false)
CreateConVar("scar_removedelay", 60, true, false)
CreateConVar("scar_useweaponammo", 1, true, false)
CreateConVar("scar_maxautostraighten", 200, true, false)